
export const chapterTitles = {

  hr: {
    "1-chapter": "Osnivanje prvih političkih stranaka",
    "2-chapter": "Oružana pobuna srba",
    "3-chapter": "Pripreme za obranu od agresora",
    "4-chapter": "Ustroj hrvatskih oružanih postrojbi",
    "5-chapter": "Oružani napad na cetinski kraj",
    "6-chapter": "Operacija južno bojište",
    "7-chapter": "Operacija Maslenica",
    "8-chapter": "Operacija Peruća",
    "9-chapter": "Boj za Veli vrh",
    "a10-chapter": "Operacija Zima",
    "b11-chapter": " Plan Z4",
    "c12-chapter": "Operacija skok 1",
    "d13-chapter": "Operacija skok 2",
    "e14-chapter": "Operacija ljeto 95",
    "f15-chapter": "Operacija oluja",
    "g16-chapter": "Operacija maestral",
    "h17-chapter": "Operacija Južni potez",
    "i18-chapter": "Unistavanje sakralnih objekata",
    "j19-chapter": "Civilne žrtve jugočetničkog terora",
  },

  en: {
    "1-chapter": "The Formation of the First Parties",
    "2-chapter": "Armed Rebellion of the Serbs",
    "3-chapter": " Preparations for defense against Serbian",
    "4-chapter": "Organization of Croatian Armed Units",
    "5-chapter": "Armed attacks on the Cetina region",
    "6-chapter": "Operation Southern Front",
    "7-chapter": "Operation Pirate Maslenica",
    "8-chapter": "Operation Peruća",
    "9-chapter": "Battle for Veli Vrh",
    "a10-chapter": "Operation Winter",
    "b11-chapter": "Plan Z4",
    "c12-chapter": "Operation Jump 1",
    "d13-chapter": "Operation Jump 2",
    "e14-chapter": "Operation summer '95",
    "f15-chapter": "Operation Storm",
    "g16-chapter": "Operation Maestral",
    "h17-chapter": "Operation Southern Maneuver",
    "i18-chapter": "Destruction of sacred objects",
    "j19-chapter": "Civilian victims of South Chetnik terror",
  },

  de: {
    "1-chapter": "Die Gründung politischen Parteien",
    "2-chapter": "Bewaffneter Aufstand der Serben",
    "3-chapter": "Vorbereitungen zur Verteidigung",
    "4-chapter": "Organisation der kroatischen  Einheiten",
    "5-chapter": "Bewaffnete Angriffe auf die Cetina-Region",
    "6-chapter": "Operation Südfront",
    "7-chapter": "Operation Pirat Maslenica",
    "8-chapter": "Operation Peruća",
    "9-chapter": "Schlacht um Veli Vrh",
    "a10-chapter": "Operation Winter",
    "b11-chapter": "Plan Z4",
    "c12-chapter": "Operation Sprung 1",
    "d13-chapter": "Operation Sprung 2",
    "e14-chapter": "Operation Sommer '95",
    "f15-chapter": "Operation Sturm",
    "g16-chapter": "Operation Maestral",
    "h17-chapter": "Operation Südliches Manöver",
    "i18-chapter": "Zerstörung heiliger Gegenstände",
    "j19-chapter": "Zivile Opfer des Süd-Tschetnik-Terrors",
  }
};
